import type {Component} from 'vue';
import {
    PhArchiveBox,
    PhArmchair,
    PhAtom,
    PhBank,
    PhBeerBottle,
    PhBell,
    PhBookOpen,
    PhBookOpenText,
    PhBooks,
    PhBracketsCurly,
    PhBrain,
    PhBriefcase,
    PhBriefcaseMetal,
    PhBroadcast,
    PhBrowsers,
    PhBug,
    PhCalculator,
    PhCalendarBlank,
    PhCalendarCheck,
    PhCamera,
    PhChalkboard,
    PhChartLineUp,
    PhChartPieSlice,
    PhChatCircle,
    PhClipboardText,
    PhClock,
    PhCloud,
    PhCloudCheck,
    PhCloudSun,
    PhCode,
    PhCoffee,
    PhCoins,
    PhConfetti,
    PhCornersOut,
    PhCpu,
    PhCreditCard,
    PhCurrencyDollar,
    PhDatabase,
    PhDesktop,
    PhDeviceMobile,
    PhDownloadSimple,
    PhEnvelope,
    PhEyedropper,
    PhFileText,
    PhFilmStrip,
    PhFlag,
    PhFlashlight,
    PhFlask,
    PhFolder,
    PhGameController,
    PhGear,
    PhGitBranch,
    PhGithubLogo,
    PhGlobe,
    PhGraduationCap,
    PhHammer,
    PhHandFist,
    PhHardDrives,
    PhHeadphones,
    PhHeart,
    PhHouse,
    PhIdentificationCard,
    PhImages,
    PhKey,
    PhLightbulb,
    PhLinkSimple,
    PhLock,
    PhMagnet,
    PhMagnifyingGlass,
    PhMegaphone,
    PhMicrophone,
    PhMusicNotes,
    PhNotebook,
    PhPaintBrush,
    PhPaperclip,
    PhPaperPlane,
    PhPawPrint,
    PhPencilLine,
    PhPhone,
    PhPiggyBank,
    PhPizza,
    PhPlanet,
    PhPopcorn,
    PhPresentationChart,
    PhPrinter,
    PhProjectorScreen,
    PhPushPin,
    PhQuestion,
    PhReceipt,
    PhRobot,
    PhRocket,
    PhRuler,
    PhScissors,
    PhScroll,
    PhShareNetwork,
    PhShieldCheck,
    PhSignature,
    PhSmiley,
    PhSpeakerHigh,
    PhSquaresFour,
    PhStack,
    PhStar,
    PhStudent,
    PhTShirt,
    PhTag,
    PhTerminal,
    PhTerminalWindow,
    PhThumbsUp,
    PhTicket,
    PhTimer,
    PhToolbox,
    PhTrash,
    PhTray,
    PhTrendUp,
    PhUploadSimple,
    PhUser,
    PhUsers,
    PhUsersThree,
    PhWallet,
    PhWifiHigh,
    PhWrench,
} from '@phosphor-icons/vue';

export const phosphorIconMap: Record<string, Component> = {
    ArchiveBox: PhArchiveBox,
    Armchair: PhArmchair,
    Atom: PhAtom,
    Bank: PhBank,
    BeerBottle: PhBeerBottle,
    Bell: PhBell,
    BookOpen: PhBookOpen,
    BookOpenText: PhBookOpenText,
    Books: PhBooks,
    BracketsCurly: PhBracketsCurly,
    Brain: PhBrain,
    Briefcase: PhBriefcase,
    BriefcaseMetal: PhBriefcaseMetal,
    Broadcast: PhBroadcast,
    Browsers: PhBrowsers,
    Bug: PhBug,
    Calculator: PhCalculator,
    CalendarBlank: PhCalendarBlank,
    CalendarCheck: PhCalendarCheck,
    Camera: PhCamera,
    Chalkboard: PhChalkboard,
    ChartLineUp: PhChartLineUp,
    ChartPieSlice: PhChartPieSlice,
    ChatCircle: PhChatCircle,
    ClipboardText: PhClipboardText,
    Clock: PhClock,
    Cloud: PhCloud,
    CloudCheck: PhCloudCheck,
    CloudSun: PhCloudSun,
    Code: PhCode,
    Coffee: PhCoffee,
    Coins: PhCoins,
    Confetti: PhConfetti,
    CornersOut: PhCornersOut,
    Cpu: PhCpu,
    CreditCard: PhCreditCard,
    CurrencyDollar: PhCurrencyDollar,
    Database: PhDatabase,
    Desktop: PhDesktop,
    DeviceMobile: PhDeviceMobile,
    DownloadSimple: PhDownloadSimple,
    Envelope: PhEnvelope,
    Eyedropper: PhEyedropper,
    FileText: PhFileText,
    FilmStrip: PhFilmStrip,
    Flag: PhFlag,
    Flashlight: PhFlashlight,
    Flask: PhFlask,
    Folder: PhFolder,
    GameController: PhGameController,
    Gear: PhGear,
    GitBranch: PhGitBranch,
    GithubLogo: PhGithubLogo,
    Globe: PhGlobe,
    GraduationCap: PhGraduationCap,
    Hammer: PhHammer,
    HandFist: PhHandFist,
    HardDrives: PhHardDrives,
    Headphones: PhHeadphones,
    Heart: PhHeart,
    House: PhHouse,
    IdentificationCard: PhIdentificationCard,
    Images: PhImages,
    Key: PhKey,
    Lightbulb: PhLightbulb,
    LinkSimple: PhLinkSimple,
    Lock: PhLock,
    Magnet: PhMagnet,
    MagnifyingGlass: PhMagnifyingGlass,
    Megaphone: PhMegaphone,
    Microphone: PhMicrophone,
    MusicNotes: PhMusicNotes,
    Notebook: PhNotebook,
    PaintBrush: PhPaintBrush,
    Paperclip: PhPaperclip,
    PaperPlane: PhPaperPlane,
    PawPrint: PhPawPrint,
    PencilLine: PhPencilLine,
    Phone: PhPhone,
    PiggyBank: PhPiggyBank,
    Pizza: PhPizza,
    Planet: PhPlanet,
    Popcorn: PhPopcorn,
    PresentationChart: PhPresentationChart,
    Printer: PhPrinter,
    ProjectorScreen: PhProjectorScreen,
    PushPin: PhPushPin,
    Question: PhQuestion,
    Receipt: PhReceipt,
    Robot: PhRobot,
    Rocket: PhRocket,
    Ruler: PhRuler,
    Scissors: PhScissors,
    Scroll: PhScroll,
    ShareNetwork: PhShareNetwork,
    ShieldCheck: PhShieldCheck,
    Signature: PhSignature,
    Smiley: PhSmiley,
    SpeakerHigh: PhSpeakerHigh,
    SquaresFour: PhSquaresFour,
    Stack: PhStack,
    Star: PhStar,
    Student: PhStudent,
    TShirt: PhTShirt,
    Tag: PhTag,
    Terminal: PhTerminal,
    TerminalWindow: PhTerminalWindow,
    ThumbsUp: PhThumbsUp,
    Ticket: PhTicket,
    Timer: PhTimer,
    Toolbox: PhToolbox,
    Trash: PhTrash,
    Tray: PhTray,
    TrendUp: PhTrendUp,
    UploadSimple: PhUploadSimple,
    User: PhUser,
    Users: PhUsers,
    UsersThree: PhUsersThree,
    Wallet: PhWallet,
    WifiHigh: PhWifiHigh,
    Wrench: PhWrench,
};

export const resolvePhosphorIcon = (name?: string, fallback = 'Question'): Component => {
    const normalized = String(name || '').replace(/^Ph/, '');
    return phosphorIconMap[normalized] ?? phosphorIconMap[fallback] ?? PhQuestion;
};
